# NAME - required
NAME = sysstate

# AUTHOR - optional
#AUTHOR = Andrey Vasilkin

# VER_xxxxx - optional
VER_MAJOR    = 0
VER_MINOR    = 0
VER_REVISION = 1

# COMMENT - optional
COMMENT = System Load utility. System status.

# LIBPATH - optional
#LIBPATH = .\

# LIBS - optional
#LIBS =

# SRCS - required
SRCS = sysstate.c

# INCPATH - optional
#INCPATH +=

# CFLAGS - optional
#CFLAGS +=

# DEBUGCODE - optional
#DEBUGCODE = yes

!include ..\utility.mif
