# PLUGIN - required
PLUGIN = sysinfo

# AUTOR - required
AUTOR = Andrey Vasilkin

# VERSION - optional
VERSION = 1.0.0

# COMMENT - optional
COMMENT = SystemLoad plugin. DosQuerySysInfo().

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib1.lib mylib2.lib

# SRCS - required
SRCS = sysinfo.c properties.c details.c

# RCFILE - optional
RCFILE = sysinfo.rc

# IPF - optional
# Source of help file. Will be compiled to <PLUGIN>.hlp
IPF = sysinfo.ipf

# INCPATH - optional
#INCPATH = .\h

# CFLAGS - optional
#CFLAGS = -zp4

# DEBUGCODE - optional
#DEBUGCODE = YES


!include ..\plugin.mif
