# NAME - required
NAME = getver

# AUTHOR - optional
#AUTHOR = Andrey Vasilkin

# VER_xxxxx - optional
VER_MAJOR    = 0
VER_MINOR    = 0
VER_REVISION = 2

# COMMENT - optional
COMMENT = System Load utility. Version signature reader.

# LIBPATH - optional
#LIBPATH = .\

# LIBS - optional
#LIBS =

# SRCS - required
SRCS = bldlevel.c getver.c

# INCPATH - optional
#INCPATH +=

# CFLAGS - optional
#CFLAGS +=

# DEBUGCODE - optional
#DEBUGCODE = yes

!include ..\utility.mif
