# PLUGIN - required
PLUGIN = os4irq

# AUTOR - required
AUTOR = Andrey Vasilkin

# VERSION - optional
VERSION = 1.0.0

# COMMENT - optional
COMMENT = SystemLoad plugin. IRQ activity monitor for OS/4 kernels.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib.lib

# SRCS - required
SRCS = os4irq.c properties.c ctxmenu.c

# RCFILE - optional
RCFILE = os4irq.rc

# CFLAGS - optional
#CFLAGS =

# DEBUGCODE - optional
#DEBUGCODE = YES


!include ..\plugin.mif
