# NAME - required
NAME = cpuid

# AUTHOR - optional
#AUTHOR = Andrey Vasilkin

# VER_xxxxx - optional
VER_MAJOR    = 1
VER_MINOR    = 1
VER_REVISION = 1

# COMMENT - optional
COMMENT = SystemLoad plugin. CPU monitor.

# LIBPATH - optional
#LIBPATH = .\

# LIBS - optional
#LIBS =

# SRCS - required
SRCS = cpuid.c

# INCPATH - optional
#INCPATH +=

# CFLAGS - optional
#CFLAGS +=

# DEBUGCODE - optional
#DEBUGCODE = yes

!include ..\utility.mif
