# PLUGIN - required
PLUGIN = sample1

# AUTOR - required
AUTOR = Andrey Vasilkin

# VERSION - optional
VERSION = 1.0.0

# COMMENT - optional
COMMENT = SystemLoad plugin. Sample 1.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib1.lib mylib2.lib

# SRCS - required
SRCS = sample1.c

# RCFILE - optional
#RCFILE = sample.rc

# INCPATH - optional
#INCPATH = .\h

# CFLAGS - optional
#CFLAGS = -zp4

# DEBUGCODE - optional
#DEBUGCODE = YES


!include ..\plugin.mif
