# NAME - required
NAME = sysinfo

# AUTHOR - optional
#AUTHOR = Andrey Vasilkin

# VER_xxxxx - optional
VER_MAJOR    = 1
VER_MINOR    = 1
VER_REVISION = 0

# COMMENT - optional
COMMENT = SystemLoad plugin. DosQuerySysInfo().

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib1.lib mylib2.lib

# SRCS - required
SRCS = sysinfo.c properties.c details.c

# RCFILE - optional
RCFILE = sysinfo.rc

# IPF - optional
# Source of help file. Will be compiled to .hlp
IPFFILE = sysinfo.ipf

# INCPATH - optional
#INCPATH = .\h

# CFLAGS - optional
#CFLAGS = -zp4

# DEBUGCODE - optional
#DEBUGCODE = yes

!include ..\plugin.mif
