# PLUGIN - required
PLUGIN = net

# AUTOR - required
AUTOR = Andrey Vasilkin

# VERSION - optional
VERSION = 1.0.1

# COMMENT - optional
COMMENT = SystemLoad plugin. Network interfaces activity monitor.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib.lib

# SRCS - required
SRCS = net.c properties.c

# RCFILE - optional
RCFILE = net.rc

# CFLAGS - optional
#CFLAGS =

# DEBUGCODE - optional
#DEBUGCODE = YES


!include ..\plugin.mif
