# PLUGIN - required
PLUGIN = traffic

# AUTOR - required
AUTOR = Andrey Vasilkin

# VERSION - optional
VERSION = 1.0.1

# COMMENT - optional
COMMENT = SystemLoad plugin. ICMP/TCP/UDP Traffic.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib1.lib mylib2.lib

# SRCS - required
SRCS = traffic.c filter.c iptrace.c statcnt.c properties.c tracewin.c defflt.c

# RCFILE - optional
RCFILE = traffic.rc

# IPF - optional
# Source of help file. Will be compiled to <PLUGIN>.hlp
IPF = traffic.ipf

# INCPATH - optional
#INCPATH = .\h

# CFLAGS - optional
#CFLAGS = -zp4

# DEBUGCODE - optional
#DEBUGCODE = YES


!include ..\plugin.mif
