# NAME - required
NAME = drives

# AUTHOR - optional
#AUTHOR = Andrey Vasilkin

# VER_xxxxx - optional
VER_MAJOR    = 1
VER_MINOR    = 1
VER_REVISION = 0

# COMMENT - optional
COMMENT = SystemLoad plugin. Drives monitor.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib.lib

# SRCS - required
SRCS = drives.c diskutil.c properties.c

# RCFILE - optional
RCFILE = drives.rc

# INCPATH - optional
#INCPATH +=.\h

# CFLAGS - optional
#CFLAGS = 

# DEBUGCODE - optional
#DEBUGCODE = yes

!include ..\plugin.mif
