# NAME - required
NAME = traffic

# AUTHOR - optional
#AUTHOR = Andrey Vasilkin

# VER_xxxxx - optional
VER_MAJOR    = 1
VER_MINOR    = 1
VER_REVISION = 0

# COMMENT - optional
COMMENT = SystemLoad plugin. ICMP/TCP/UDP Traffic.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib1.lib mylib2.lib

# SRCS - required
SRCS = traffic.c filter.c iptrace.c statcnt.c properties.c tracewin.c defflt.c

# RCFILE - optional
RCFILE = traffic.rc

# IPF - optional
# Source of help file. Will be compiled to .hlp
IPFFILE = traffic.ipf

# INCPATH - optional
#INCPATH = .\h

# CFLAGS - optional
#CFLAGS = -zp4

# DEBUGCODE - optional
#DEBUGCODE = yes

!include ..\plugin.mif
