# PLUGIN - required
PLUGIN = cpu

# AUTOR - required
AUTOR = Andrey Vasilkin

# VERSION - optional
VERSION = 1.1.0

# COMMENT - optional
COMMENT = SystemLoad plugin. CPU monitor.

# LIBPATH - optional
#LIBPATH = .\

# LIBS - optional
LIBS = cputemp.lib

# SRCS - required
SRCS = cpu.c properties.c ctxmenu.c termzone.c features.c

# RCFILE - optional
RCFILE = cpu.rc

# IPF - optional
# Source of help file. Will be compiled to <PLUGIN>.hlp
IPF = cpu.ipf

# INCPATH - optional
# Header files from ACPI Toolkit.
INCPATH = .\h

# CFLAGS - optional
# ACPI Toolkit samples uses flag -zp4.
CFLAGS = -zp4

# DEBUGCODE - optional
#DEBUGCODE = YES


!include ..\plugin.mif
