# PLUGIN - required
PLUGIN = cpu

# AUTOR - required
AUTOR = Andrey Vasilkin

# VERSION - optional
VERSION = 1.0.0

# COMMENT - optional
COMMENT = SystemLoad plugin. CPU monitor.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
# No need lib. - acpi32.dll loads is dynamically.
#LIBS = acpi32.lib

# SRCS - required
SRCS = cpu.c properties.c ctxmenu.c proctemp.c features.c

# RCFILE - optional
RCFILE = cpu.rc

# INCPATH - optional
# Header files from ACPI Toolkit.
INCPATH = .\h

# CFLAGS - optional
# ACPI Toolkit samples uses flag -zp4.
CFLAGS = -zp4

# DEBUGCODE - optional
#DEBUGCODE = YES


!include ..\plugin.mif
