# PLUGIN - required
PLUGIN = sample3

# AUTOR - required
AUTOR = Andrey Vasilkin

# VERSION - optional
VERSION = 1.0.0

# COMMENT - optional
COMMENT = SystemLoad plugin. Sample 3.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib1.lib mylib2.lib

# SRCS - required
SRCS = sample3.c

# RCFILE - optional
RCFILE = sample3.rc

# INCPATH - optional
#INCPATH = .\h

# CFLAGS - optional
#CFLAGS = -zp4

# DEBUGCODE - optional
#DEBUGCODE = YES


!include ..\plugin.mif
