# NAME - required
NAME = net

# AUTHOR - optional
#AUTHOR = Andrey Vasilkin

# VER_xxxxx - optional
VER_MAJOR    = 1
VER_MINOR    = 1
VER_REVISION = 0

# COMMENT - optional
COMMENT = SystemLoad plugin. Network interfaces activity monitor.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib.lib

# SRCS - required
SRCS = net.c properties.c

# RCFILE - optional
RCFILE = net.rc

# CFLAGS - optional
#CFLAGS =

# DEBUGCODE - optional
#DEBUGCODE = yes

!include ..\plugin.mif
