# NAME - required
NAME = sample1

# AUTHOR - optional
AUTHOR = Andrey Vasilkin

# VER_xxxxx - optional
VER_MAJOR    = 0
VER_MINOR    = 0
VER_REVISION = 1

# COMMENT - optional
COMMENT = SystemLoad plugin. Sample 1.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib1.lib mylib2.lib

# SRCS - required
SRCS = sample1.c

# RCFILE - optional
#RCFILE = sample.rc

# INCPATH - optional
#INCPATH = .\h

# CFLAGS - optional
#CFLAGS = -zp4

# DEBUGCODE - optional
#DEBUGCODE = yes

!include ..\plugin.mif

