#define IDS_CELSIUS_UM         1
#define IDS_FAHRENHEIT_UM      2
#define IDS_CPU                3
#define IDS_OFFLINE            4
#define IDS_CELSIUS_ITEM       5
#define IDS_FAHRENHEIT_ITEM    6
#define IDS_UNSUPPORTED_CPU    7
#define IDS_INVALID_VALUE      8
#define IDS_NO_DRIVER          9
