# PLUGIN - required
PLUGIN = drives

# AUTOR - required
AUTOR = Andrey Vasilkin

# VERSION - optional
VERSION = 1.0.3

# COMMENT - optional
COMMENT = SystemLoad plugin. Drives monitor.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib.lib

# SRCS - required
SRCS = drives.c diskutil.c properties.c

# RCFILE - optional
RCFILE = drives.rc

# INCPATH - optional
#INCPATH = .\h

# CFLAGS - optional
#CFLAGS = 

# DEBUGCODE - optional
#DEBUGCODE = YES


!include ..\plugin.mif
