# NAME - required
NAME = os4irq

# AUTHOR - optional
#AUTHOR = Andrey Vasilkin

# VER_xxxxx - optional
VER_MAJOR    = 1
VER_MINOR    = 1
VER_REVISION = 0

# COMMENT - optional
COMMENT = SystemLoad plugin. IRQ activity monitor for OS/4 kernels.

# LIBPATH - optional
#LIBPATH = D:\my\lib\path

# LIBS - optional
#LIBS = mylib.lib

# SRCS - required
SRCS = os4irq.c properties.c ctxmenu.c irqlist.c

# LIBS - optional
LIBS = $(DDKPATH)\base32\rel\os2c\lib\os2\kee.lib

# RCFILE - optional
RCFILE = os4irq.rc

# CFLAGS - optional
#CFLAGS =

# DEBUGCODE - optional
#DEBUGCODE = yes

!include ..\plugin.mif
